# Until https://github.com/julia-actions/julia-uploadcodecov/issues/1 get fixed
# submit coverage report via travis
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false

jobs:
  include:
    - stage: deploy
      julia: 1.0
      os: linux
      script:
        - julia -e 'import Pkg; Pkg.add(["Documenter", "Unitful"])'
        - julia -e 'import ImageAxes; include("docs/make.jl")'

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
